str1=input("Enter the string of 4 character in lowercase:")
ch1=ord(str1[0].upper())
ch2=ord(str1[1].upper())
ch3=ord(str1[2].upper())
ch4=ord(str1[3].upper())

print(str1[0],ch1,end=' ')
print(str1[1],ch2,end=' ')
print(str1[2],ch3,end=' ')
print(str1[3],ch4,end=' ')